language: ruby
os: linux
dist: trusty
rvm:
- 2.4.1
install: gem install jekyll -v 3.8.0 && gem install jekyll-redirect-from && gem install
  s3_website
script: jekyll build
after_success:
- test $TRAVIS_BRANCH = "production" && s3_website push --config-dir=_config/production/
- test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/
branches:
  only:
  - master
  - staging
