language: ruby
os: linux
dist: trusty
rvm:
- 2.4.1
install: bundle install && gem install s3_website
script:
- bundle exec jekyll build
after_success:
- test $TRAVIS_BRANCH = "production" && s3_website push --config-dir=_config/production/
- test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/
branches:
  only:
  - production
  - staging
notifications:
  slack:
    secure: MdbQ6X88By5MpJ+kAp/1x42rrXWxmESd6Z8c9zM3zXFs1iUfk/Y+Z0tOFaynJhoN1i4qoRXzmJktTR4v9Sk/19lAO2vfHIdobwM2TWNmceMud89l87SeOsK4TbnsS+bsqLfASjAMMzFd3hVAnnV4BI4AqHiaHZ4Ua2C95AOldW9UygoYnzUTwqtRelTKqdejRZdWPPYC1ZANKGC42DEBBhUCKOKw696pjDmWF/AyUYAIKYvAN47xBe2c203V+yub52qxMBBjZyrpuIXskuMRD4ERzkBiAYuw2b5tffJuMViDxUnqiG+j+7gmn3Ug/0T6N+KpqGY2pOZ9UfpZEy0DUShtPPuWsDArpqcKGmTR35CUJtVEi0TsLrS9ZFnhwwpepYEIsTtwqlkSiO4p1poN8r7DqliGtEm2YOSvn9RYnQRUYMGKOY09rfz0SxMeYn3CSrznyuT2BjUSNRp7ZPGolLENYFnXJYXbb+jNhUSMvrARGjsUe77NrZnYrOm9d9FpFVe0CmMviRpVpuguJguJtu+4W7bUjWE0Ydpc157d9ob1ykEd2puk60Sca1Iv5RaTngRcfHT05gMYHXNxU+NZWc58QyJFNmvYfHuox1gqst7aqODAHuuXKcuYaQ2yJXUrklW8ny3elqU8ei72wFLS4Xh0ikya33eW1lkLVE1qanQ=
