# Site settings

title: Lived Experience Project
email: your-email@example.com
description: >-
  The Lived Experience Project is an Omaha-based
  juvenile justice research and facilitation project
  that centers the experiences of system impacted youth
  and their families.
credits:
author: jeff
baseurl: ""
url: "/about/lex"
twitter_username: jsguntzel
github_username:  jsguntzel

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  # - jekyll/tagging

tag_page_layout: tag_page
tag_page_dir: topic
tag_permalink_style: pretty
tag_title_prefix: "Posts Tagged &ldquo;"
tag_title_suffix: "&rdquo;"
author_dir: /team
author_title_prefix: "Team Member: "
category_dir: "/category"
category_title_prefix: ''

audio_base_path: /media/audio
video_base_path: /media/video

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: ''

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/images/'

# Logo size is 600x80 pixels
logo: "logo.png"

paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
permalink          : /:year/:month/:day/:title/
# permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
# Exclude these files from your production _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - vendor
  - '*.yml'
  - '.DS_Store'

# The language setting is used in /includes/header.html for html-settings
language: 'en'

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      breadcrumb: true
      show_meta: false  # Hide metadata for all pages
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jeff     # Default author for pages
      header:
        image_fullwidth: lex-healing.jpg
        caption: Artwork by Odera Igbokwe
        caption_url: https://www.odera.net/
  -
    scope:
      path: 'pages/about/*'        # an empty string here means all files in the project
      type: 'pages'
    values:
      breadcrumb: true
      show_meta: false  # Hide metadata for all pages
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jeff     # Default author for pages
      header:
        image_fullwidth: lex-healing.jpg
        caption:  Artwork by Odera Igbokwe
        caption_url: https://www.odera.net/
  -
    scope:
      path: ''
      type: 'posts'
    values:
      breadcrumb: false
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jeff     # Default author for posts
      header:
        image_fullwidth: lex-healing.jpg
        caption: Artwork by Odera Igbokwe
        caption_url: https://www.odera.net/

google_author:             'https://plus.google.com/u/0/xxxxx'
google_site_verification:  'xxxxx'
bing_webmastertools_id:    'xxxxx'
# yandex_site_verification:  ''
# alexa_verify_id:           ''

og_image:                           ''
og_locale:                          'en_EN'
og_type:                            'website'

socialmedia:
    twitter: xxxxxx
    facebook: xxxxxxx
    instagram: xxxxxxx

# used in _includes/comments

disqus_shortname: livedexperience

sass:
    sass_dir : _sass
    style    : :compressed
    sourcemap: true

# used in _includes/footer_scripts

# google_analytics_tracking_id:

# asciidoctor-enabled: false
# asciidoctor:
#   description:
#   attributes:
#     source-highlighter: coderay
#     coderay-css: style
#     icons: font
